from typing import Any


def generate_markdown_report(report: dict[str, Any]) -> str:
    summary = report.get("session_summary", {})
    data_quality = report.get("data_quality", {})
    lines = [
        f"# Session Report: {report.get('session_id')}",
        "",
        "## Summary",
        f"- Classification: {summary.get('classification')} ({summary.get('classification_confidence')})",
        f"- Generated at: {report.get('generated_at')}",
        "",
        "## File Inventory",
    ]
    operator_report = report.get("operator_report") or {}
    if operator_report:
        state = operator_report.get("state") or {}
        confidence = operator_report.get("confidence") or {}
        lines[6:6] = [
            "## Итог для оператора",
            f"- Состояние: {state.get('label_ru') or 'нет вывода'}",
            f"- Уверенность анализа: {confidence.get('level_ru') or 'не определена'} "
            f"({confidence.get('score')})",
            "- Возможные причины являются гипотезами и требуют проверки.",
            "",
            "### Отклонения",
            *(
                [f"- {item.get('title')}: {item.get('detail')}" for item in operator_report.get("deviations", [])]
                or ["- Существенных отклонений не обнаружено."]
            ),
            "",
            "### Рекомендации",
            *[f"- {item}" for item in operator_report.get("recommendations", [])],
            "",
        ]
    for item in report.get("file_inventory", []):
        lines.append(
            f"- {item['path']}: {item['family']} / {item['role']}, {item['size_bytes']} bytes, quality={item['data_quality_status']}"
        )
    lines.extend(["", "## Timeline And Phases"])
    for segment in report.get("phase_segments", []):
        lines.append(f"- {segment.get('phase')}: {segment.get('ts_start')} -> {segment.get('ts_end')}")
    lines.extend(["", "## Anomalies"])
    anomalies = report.get("anomalies", [])
    if anomalies:
        for anomaly in anomalies:
            lines.append(f"- {anomaly.get('anomaly_type')}: severity={anomaly.get('severity')}, confidence={anomaly.get('confidence')}")
    else:
        lines.append("- No deterministic anomalies were generated by the current rule/statistical layer.")
    lines.extend(["", "## Operator And Production Context"])
    context = report.get("operator_context", {})
    if context:
        for key, value in context.items():
            lines.append(f"- {key}: {value}")
    else:
        lines.append("- Missing or unconfirmed operator context.")
    lines.extend(["", "## Quality Outcomes"])
    outcomes = report.get("quality_outcomes", [])
    if outcomes:
        for outcome in outcomes:
            lines.append(f"- {outcome.get('inspection_type')}: {outcome.get('result')} {outcome.get('defect_type') or ''}".rstrip())
    else:
        lines.append("- No linked quality outcomes.")
    lines.extend(["", "## Data Quality"])
    lines.append(f"- Empty files: {len(data_quality.get('empty_files', []))}")
    lines.append(f"- Malformed rows recovered: {data_quality.get('malformed_rows', 0)}")
    lines.append(f"- Repeated headers ignored: {data_quality.get('repeated_headers', 0)}")
    for note in data_quality.get("notes", []):
        lines.append(f"- {note}")
    lines.extend(["", "## Version Metadata"])
    version_metadata = report.get("version_metadata", {})
    for key, value in version_metadata.items():
        if key != "input_file_hashes":
            lines.append(f"- {key}: {value}")
    insights = report.get("log_insights") or {}
    if insights:
        lines.extend(["", "## Послойная диагностика"])
        for metric in (insights.get("environment") or {}).get("metrics", []):
            lines.append(
                f"- {metric['name_ru']}: превышение порога {metric['exceedance_seconds']:.2f} с; "
                f"интеграл {metric['excess_integral']:.3f} {metric['integral_unit']}; "
                f"покрытие {(metric.get('coverage_ratio') or 0)*100:.1f}%."
            )
        for item in (insights.get("time_accounting") or {}).get("components", []):
            lines.append(f"- {item['name_ru']}: {item['seconds']:.2f} с.")
        lines.append("- Превышение порога не доказывает дефект; необъяснённая задержка не считается подтверждённой паузой.")
    return "\n".join(lines) + "\n"
