from typing import Any


def generate_markdown_report(report: dict[str, Any]) -> str:
    summary = report.get("session_summary", {})
    data_quality = report.get("data_quality", {})
    lines = [
        f"# Session Report: {report.get('session_id')}",
        "",
        "## Summary",
        f"- Classification: {summary.get('classification')} ({summary.get('classification_confidence')})",
        f"- Generated at: {report.get('generated_at')}",
        "",
        "## File Inventory",
    ]
    for item in report.get("file_inventory", []):
        lines.append(
            f"- {item['path']}: {item['family']} / {item['role']}, {item['size_bytes']} bytes, quality={item['data_quality_status']}"
        )
    lines.extend(["", "## Timeline And Phases"])
    for segment in report.get("phase_segments", []):
        lines.append(f"- {segment.get('phase')}: {segment.get('ts_start')} -> {segment.get('ts_end')}")
    lines.extend(["", "## Anomalies"])
    anomalies = report.get("anomalies", [])
    if anomalies:
        for anomaly in anomalies:
            lines.append(f"- {anomaly.get('anomaly_type')}: severity={anomaly.get('severity')}, confidence={anomaly.get('confidence')}")
    else:
        lines.append("- No deterministic anomalies were generated by the current rule/statistical layer.")
    lines.extend(["", "## Operator And Production Context"])
    context = report.get("operator_context", {})
    if context:
        for key, value in context.items():
            lines.append(f"- {key}: {value}")
    else:
        lines.append("- Missing or unconfirmed operator context.")
    lines.extend(["", "## Quality Outcomes"])
    outcomes = report.get("quality_outcomes", [])
    if outcomes:
        for outcome in outcomes:
            lines.append(f"- {outcome.get('inspection_type')}: {outcome.get('result')} {outcome.get('defect_type') or ''}".rstrip())
    else:
        lines.append("- No linked quality outcomes.")
    lines.extend(["", "## Data Quality"])
    lines.append(f"- Empty files: {len(data_quality.get('empty_files', []))}")
    lines.append(f"- Malformed rows recovered: {data_quality.get('malformed_rows', 0)}")
    lines.append(f"- Repeated headers ignored: {data_quality.get('repeated_headers', 0)}")
    for note in data_quality.get("notes", []):
        lines.append(f"- {note}")
    lines.extend(["", "## Version Metadata"])
    version_metadata = report.get("version_metadata", {})
    for key, value in version_metadata.items():
        if key != "input_file_hashes":
            lines.append(f"- {key}: {value}")
    return "\n".join(lines) + "\n"

