from datetime import datetime, timezone
from typing import Any
from uuid import uuid4


def create_pattern_insight_draft(hypothesis: dict[str, Any], analysis_window: dict[str, Any]) -> dict[str, Any]:
    return {
        "insight_id": f"insight_{uuid4().hex}",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "updated_at": datetime.now(timezone.utc).isoformat(),
        "analysis_window": analysis_window,
        "scope_filters": {},
        "insight_type": "recurring_pattern",
        "title": hypothesis["title"],
        "description": "Draft insight generated by bounded historical analysis; requires human review.",
        "supporting_sessions": hypothesis.get("supporting_sessions", []),
        "supporting_events": [],
        "counterexamples": [],
        "sample_size": hypothesis.get("causal_data_quality", {}).get("sample_size", 0),
        "effect_size": None,
        "confidence": hypothesis.get("confidence", 0.0),
        "causal_data_quality": hypothesis.get("causal_data_quality", {}),
        "status": "needs_review",
        "generated_by": "background_reanalysis",
        "analysis_version": "0.1.0",
        "recommended_action": "Engineer review required before promoting to confirmed knowledge.",
        "audit_trail": [{"action": "created_as_draft"}],
    }

