"""Export Docker/CI requirements from pyproject without resolving or installing.

Native requirements keep their declared version ranges. The existing Python
3.11 container pins are explicitly maintained in the same pyproject; they are
not a transitive lock and must not be replaced by a host-specific pip freeze.
Only Python 3.11's standard library is required, including for --check in CI.
"""
from __future__ import annotations

import argparse
from pathlib import Path
import re
import sys
import tomllib

ROOT = Path(__file__).resolve().parents[1]
TIERS = {
    "base": "Core web/infrastructure; every service image.",
    "analytics": "Analytics wheels; worker, scheduler and API/estimator.",
    "heavy": "Geometry/ML and optional showcase; API/estimator image only.",
    "dev": "Test and lint tools; CI/development only.",
    "mcp": "Optional MCP service, layered on base.",
}
_REQUIREMENT = re.compile(r"^([A-Za-z0-9][A-Za-z0-9._-]*)(\[[A-Za-z0-9_,. -]+\])?(.*)$")
_VERSION = re.compile(r"^\d+(?:\.\d+)*$")


def canonical_name(value: str) -> str:
    return re.sub(r"[-_.]+", "-", value).lower()


def _version(value: str) -> tuple[int, ...]:
    if not _VERSION.fullmatch(value):
        raise ValueError(f"Unsupported container pin {value!r}; use a numeric release version")
    parts = [int(part) for part in value.split(".")]
    while len(parts) > 1 and parts[-1] == 0:
        parts.pop()
    return tuple(parts)


def _apply_pin(name: str, extras: str, spec: str, pin: str) -> str:
    # Deliberately fail rather than silently misinterpret a new PEP 508 marker,
    # prerelease, upper bound or URL. Extend validation with tests when needed.
    constraint = re.fullmatch(r"(>=|==)(\d+(?:\.\d+)*)", spec.strip())
    if constraint is None:
        raise ValueError(f"Cannot validate pin against {name}{extras}{spec!s}")
    relation, declared = constraint.groups()
    if (_version(pin) < _version(declared)
            or relation == "==" and _version(pin) != _version(declared)):
        raise ValueError(f"Container pin {name}=={pin} contradicts declared {name}{spec}")
    return f"{name}{extras}=={pin}"


def render_requirements(project: dict) -> dict[str, str]:
    config = project["tool"]["printer-companion"]["dependencies"]
    if unknown := config.keys() - (TIERS.keys() | {"native-only", "pins"}):
        raise ValueError(f"Unknown dependency tiers: {', '.join(sorted(unknown))}")
    declarations: dict[str, tuple[str, str, str]] = {}
    requirement_strings = list(project["project"]["dependencies"])
    for group in project["project"].get("optional-dependencies", {}).values():
        requirement_strings.extend(group)
    for requirement in requirement_strings:
        match = _REQUIREMENT.fullmatch(requirement)
        if match is None:
            raise ValueError(f"Invalid requirement declaration {requirement!r}")
        name, extras, spec = match.groups()
        key = canonical_name(name)
        value = (name, extras or "", spec)
        if key in declarations and declarations[key] != value:
            raise ValueError(f"Conflicting dependency declaration for {name}")
        declarations[key] = value

    pins = {canonical_name(name): value for name, value in config.get("pins", {}).items()}
    assigned: dict[str, str] = {}
    outputs = {}
    for tier in (*TIERS, "native-only"):
        lines = []
        for name in config[tier]:
            key = canonical_name(name)
            if key not in declarations:
                raise ValueError(f"Undeclared dependency {name} in tier {tier}")
            if key in assigned:
                raise ValueError(f"Dependency {name} belongs to both {assigned[key]} and {tier}")
            assigned[key] = tier
            declared_name, extras, spec = declarations[key]
            line = f"{declared_name}{extras}{spec}"
            if key in pins:
                line = _apply_pin(declared_name, extras, spec, pins[key])
            lines.append(line)
        if tier in TIERS:
            outputs[f"requirements.{tier}.txt"] = (
                "# Generated by scripts/export_requirements.py from pyproject.toml; do not edit.\n"
                f"# {TIERS[tier]}\n"
                "# Direct requirements only, not a cross-platform/transitive lock.\n"
                + "\n".join(lines) + "\n"
            )
    if missing := declarations.keys() - assigned.keys():
        raise ValueError(f"Dependencies without an explicit tier: {', '.join(sorted(missing))}")
    if unused := pins.keys() - assigned.keys():
        raise ValueError(f"Pins without a declared dependency: {', '.join(sorted(unused))}")
    return outputs


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Check projections without changing files")
    parser.add_argument("--root", type=Path, default=ROOT, help="Project root (also useful for fixture tests)")
    args = parser.parse_args(argv)
    try:
        project = tomllib.loads((args.root / "pyproject.toml").read_text(encoding="utf-8"))
        outputs = render_requirements(project)
    except (OSError, ValueError, KeyError, TypeError) as exc:
        print(f"Dependency declaration error: {exc}", file=sys.stderr)
        return 2
    stale = []
    for name, expected in outputs.items():
        path = args.root / name
        actual = path.read_text(encoding="utf-8") if path.is_file() else None
        if actual != expected:
            stale.append(name)
            if not args.check:
                path.write_text(expected, encoding="utf-8")
    if args.check and stale:
        print("Stale requirements: " + ", ".join(stale), file=sys.stderr)
        print("Run python scripts/export_requirements.py and review the generated diff.", file=sys.stderr)
        return 1
    print("Requirements match pyproject.toml" if args.check else "Updated: " + (", ".join(stale) or "none"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
