name: Deploy to Windows

on:
  push:
    branches: [main]
  workflow_dispatch:  # кнопка ручного запуска на GitHub

jobs:
  deploy:
    runs-on: self-hosted
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restart services
        shell: cmd
        run: |
          docker compose up -d --build --remove-orphans
          docker compose ps
